### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by lanshijie** [XGG17/HuaBanDemo#1]
- (void)drawRect:(CGRect)rect {
  
  // 把所有路径画出来
  for (DrawPath *path in self.pathArr) {
  
  ```
  if ([path isKindOfClass:[UIImage class]]) {
      // 画图
      UIImage *image = (UIImage *)path;
      [image drawInRect:rect];
  }else {
      // 画线
      [path.pathColor set];
      [path stroke];
  }
  ```
  
  }
  }

画图那个分支什么时候会进入，不是很懂，

**Comment by XGG17** [comment]
这个demo只有画线。如果需要将图片在画板上展示出来，首先将图片存放在self.pathArr中，在调用drawRect时就会进入画图分支

**Comment by XGG17** [comment]
这个demo只有画线。如果需要将图片在画板上展示出来，首先将图片存放在self.pathArr中，在调用drawRect时就会进入画图分支 @lanshijie
